<?php

declare(strict_types=1);

namespace Database\Seeders\Properties;

use App\Models\Property;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    use WithoutModelEvents;

    private const PAYLOAD = [
        [
            Property::FLAT_NUMBER => 101,
            Property::FLOOR => 1,
            Property::TERRACE_AREA => 49.00,
            Property::BALCONY_AREA => null,
            Property::FLAT_AREA => 49.94,
            Property::TOTAL_AREA => 98.94,
            Property::PRICE => 20000000,
        ],
        [
            Property::FLAT_NUMBER => 102,
            Property::FLOOR => 1,
            Property::TERRACE_AREA => 63.00,
            Property::BALCONY_AREA => null,
            Property::FLAT_AREA => 105.54,
            Property::TOTAL_AREA => 168.54,
            Property::PRICE => 25000000,
        ],
        [
            Property::FLAT_NUMBER => 103,
            Property::FLOOR => 1,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => null,
            Property::FLAT_AREA => 67.72,
            Property::TOTAL_AREA => 67.72,
            Property::PRICE => 15000000,
        ],
        [
            Property::FLAT_NUMBER => 104,
            Property::FLOOR => 1,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => null,
            Property::FLAT_AREA => 57.94,
            Property::TOTAL_AREA => 57.94,
            Property::PRICE => 13500000,
        ],
        [
            Property::FLAT_NUMBER => 105,
            Property::FLOOR => 1,
            Property::TERRACE_AREA => 91.00,
            Property::BALCONY_AREA => null,
            Property::FLAT_AREA => 127.66,
            Property::TOTAL_AREA => 218.66,
            Property::PRICE => 27500000,
        ],
        [
            Property::FLAT_NUMBER => 106,
            Property::FLOOR => 1,
            Property::TERRACE_AREA => 23.00,
            Property::BALCONY_AREA => null,
            Property::FLAT_AREA => 46.10,
            Property::TOTAL_AREA => 69.10,
            Property::PRICE => 15500000,
        ],
        [
            Property::FLAT_NUMBER => 201,
            Property::FLOOR => 2,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 19.52,
            Property::FLAT_AREA => 73.33,
            Property::TOTAL_AREA => 92.85,
            Property::PRICE => 28500000,
        ],
        [
            Property::FLAT_NUMBER => 202,
            Property::FLOOR => 2,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 18.88,
            Property::FLAT_AREA => 97.12,
            Property::TOTAL_AREA => 116,
            Property::PRICE => 23200000,
        ],
        [
            Property::FLAT_NUMBER => 203,
            Property::FLOOR => 2,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 12.85,
            Property::FLAT_AREA => 119.01,
            Property::TOTAL_AREA => 131.86,
            Property::PRICE => 28200000,
        ],
        [
            Property::FLAT_NUMBER => 204,
            Property::FLOOR => 2,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 9.34,
            Property::FLAT_AREA => 64.77,
            Property::TOTAL_AREA => 74.11,
            Property::PRICE => 19200000,
        ],
        [
            Property::FLAT_NUMBER => 205,
            Property::FLOOR => 2,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 8.4,
            Property::FLAT_AREA => 95.36,
            Property::TOTAL_AREA => 103.76,
            Property::PRICE => 21200000,
        ],
        [
            Property::FLAT_NUMBER => 206,
            Property::FLOOR => 2,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 8.95,
            Property::FLAT_AREA => 56.9,
            Property::TOTAL_AREA => 65.85,
            Property::PRICE => 15200000,
        ],
        [
            Property::FLAT_NUMBER => 207,
            Property::FLOOR => 2,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 12.46,
            Property::FLAT_AREA => 100.3,
            Property::TOTAL_AREA => 112.76,
            Property::PRICE => 17800000,
        ],
        [
            Property::FLAT_NUMBER => 208,
            Property::FLOOR => 2,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 7.05,
            Property::FLAT_AREA => 61.16,
            Property::TOTAL_AREA => 68.21,
            Property::PRICE => 14900000,
        ],
        [
            Property::FLAT_NUMBER => 209,
            Property::FLOOR => 2,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 14.93,
            Property::FLAT_AREA => 97.26,
            Property::TOTAL_AREA => 112.19,
            Property::PRICE => 17200000,
        ],
        [
            Property::FLAT_NUMBER => 210,
            Property::FLOOR => 2,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 20.17,
            Property::FLAT_AREA => 112.85,
            Property::TOTAL_AREA => 133.02,
            Property::PRICE => 18100000,
        ],
        [
            Property::FLAT_NUMBER => 211,
            Property::FLOOR => 2,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 4.1,
            Property::FLAT_AREA => 91.38,
            Property::TOTAL_AREA => 95.48,
            Property::PRICE => 14500000,
        ],
        // Floor 3
        [
            Property::FLAT_NUMBER => 301,
            Property::FLOOR => 3,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 19.52,
            Property::FLAT_AREA => 74.91,
            Property::TOTAL_AREA => 94.43,
            Property::PRICE => 19850000,
        ],
        [
            Property::FLAT_NUMBER => 302,
            Property::FLOOR => 3,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 24.36,
            Property::FLAT_AREA => 91.64,
            Property::TOTAL_AREA => 116,
            Property::PRICE => 24100000,
        ],
        [
            Property::FLAT_NUMBER => 303,
            Property::FLOOR => 3,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 12.85,
            Property::FLAT_AREA => 119.01,
            Property::TOTAL_AREA => 131.86,
            Property::PRICE => 28750000,
        ],
        [
            Property::FLAT_NUMBER => 304,
            Property::FLOOR => 3,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 9.34,
            Property::FLAT_AREA => 64.78,
            Property::TOTAL_AREA => 74.12,
            Property::PRICE => 16400000,
        ],
        [
            Property::FLAT_NUMBER => 305,
            Property::FLOOR => 3,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 8.4,
            Property::FLAT_AREA => 95.36,
            Property::TOTAL_AREA => 103.76,
            Property::PRICE => 21850000,
        ],
        [
            Property::FLAT_NUMBER => 306,
            Property::FLOOR => 3,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 8.95,
            Property::FLAT_AREA => 56.9,
            Property::TOTAL_AREA => 65.85,
            Property::PRICE => 14750000,
        ],
        [
            Property::FLAT_NUMBER => 307,
            Property::FLOOR => 3,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 15.98,
            Property::FLAT_AREA => 96.78,
            Property::TOTAL_AREA => 112.76,
            Property::PRICE => 23200000,
        ],
        [
            Property::FLAT_NUMBER => 308,
            Property::FLOOR => 3,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 7.05,
            Property::FLAT_AREA => 61.16,
            Property::TOTAL_AREA => 68.21,
            Property::PRICE => 15300000,
        ],
        [
            Property::FLAT_NUMBER => 309,
            Property::FLOOR => 3,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 14.93,
            Property::FLAT_AREA => 97.27,
            Property::TOTAL_AREA => 112.2,
            Property::PRICE => 22650000,
        ],
        [
            Property::FLAT_NUMBER => 310,
            Property::FLOOR => 3,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 20.17,
            Property::FLAT_AREA => 112.85,
            Property::TOTAL_AREA => 133.02,
            Property::PRICE => 27400000,
        ],
        [
            Property::FLAT_NUMBER => 311,
            Property::FLOOR => 3,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 4.1,
            Property::FLAT_AREA => 91.38,
            Property::TOTAL_AREA => 95.48,
            Property::PRICE => 19200000,
        ],
        // Floor 4
        [
            Property::FLAT_NUMBER => 401,
            Property::FLOOR => 4,
            Property::TERRACE_AREA => 173,
            Property::BALCONY_AREA => 19.52,
            Property::FLAT_AREA => 74.48,
            Property::TOTAL_AREA => 267,
            Property::PRICE => 45200000,
        ],
        [
            Property::FLAT_NUMBER => 402,
            Property::FLOOR => 4,
            Property::TERRACE_AREA => 90,
            Property::BALCONY_AREA => 18.88,
            Property::FLAT_AREA => 97.12,
            Property::TOTAL_AREA => 206,
            Property::PRICE => 38500000,
        ],
        [
            Property::FLAT_NUMBER => 403,
            Property::FLOOR => 4,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 12.85,
            Property::FLAT_AREA => 119.01,
            Property::TOTAL_AREA => 131.86,
            Property::PRICE => 29100000,
        ],
        [
            Property::FLAT_NUMBER => 404,
            Property::FLOOR => 4,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 9.34,
            Property::FLAT_AREA => 64.78,
            Property::TOTAL_AREA => 74.12,
            Property::PRICE => 16750000,
        ],
        [
            Property::FLAT_NUMBER => 405,
            Property::FLOOR => 4,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 8.4,
            Property::FLAT_AREA => 95.36,
            Property::TOTAL_AREA => 103.76,
            Property::PRICE => 22100000,
        ],
        [
            Property::FLAT_NUMBER => 406,
            Property::FLOOR => 4,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 8.95,
            Property::FLAT_AREA => 56.9,
            Property::TOTAL_AREA => 65.85,
            Property::PRICE => 15050000,
        ],
        [
            Property::FLAT_NUMBER => 407,
            Property::FLOOR => 4,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 15.98,
            Property::FLAT_AREA => 96.78,
            Property::TOTAL_AREA => 112.76,
            Property::PRICE => 23550000,
        ],
        [
            Property::FLAT_NUMBER => 408,
            Property::FLOOR => 4,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 7.05,
            Property::FLAT_AREA => 61.16,
            Property::TOTAL_AREA => 68.21,
            Property::PRICE => 15600000,
        ],
        [
            Property::FLAT_NUMBER => 409,
            Property::FLOOR => 4,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 14.93,
            Property::FLAT_AREA => 97.27,
            Property::TOTAL_AREA => 112.2,
            Property::PRICE => 22900000,
        ],
        [
            Property::FLAT_NUMBER => 410,
            Property::FLOOR => 4,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 20.17,
            Property::FLAT_AREA => 112.87,
            Property::TOTAL_AREA => 133.04,
            Property::PRICE => 27850000,
        ],
        [
            Property::FLAT_NUMBER => 411,
            Property::FLOOR => 4,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 4.1,
            Property::FLAT_AREA => 91.38,
            Property::TOTAL_AREA => 95.48,
            Property::PRICE => 19650000,
        ],
        // Floor 5
        [
            Property::FLAT_NUMBER => 501,
            Property::FLOOR => 5,
            Property::TERRACE_AREA => 15.5,
            Property::BALCONY_AREA => null,
            Property::FLAT_AREA => 113.27,
            Property::TOTAL_AREA => 128.77,
            Property::PRICE => 31200000,
        ],
        [
            Property::FLAT_NUMBER => 502,
            Property::FLOOR => 5,
            Property::TERRACE_AREA => 146,
            Property::BALCONY_AREA => null,
            Property::FLAT_AREA => 118.81,
            Property::TOTAL_AREA => 264.81,
            Property::PRICE => 52300000,
        ],
        [
            Property::FLAT_NUMBER => 503,
            Property::FLOOR => 5,
            Property::TERRACE_AREA => null,
            Property::BALCONY_AREA => 6.78,
            Property::FLAT_AREA => 61.17,
            Property::TOTAL_AREA => 67.95,
            Property::PRICE => 16100000,
        ],
        [
            Property::FLAT_NUMBER => 504,
            Property::FLOOR => 5,
            Property::TERRACE_AREA => 101,
            Property::BALCONY_AREA => 3.94,
            Property::FLAT_AREA => 126.93,
            Property::TOTAL_AREA => 231.87,
            Property::PRICE => 47800000,
        ],
        [
            Property::FLAT_NUMBER => 505,
            Property::FLOOR => 5,
            Property::TERRACE_AREA => 9.2,
            Property::BALCONY_AREA => null,
            Property::FLAT_AREA => 97.03,
            Property::TOTAL_AREA => 106.23,
            Property::PRICE => 26400000,
        ],
    ];

    public function run(): void
    {
        foreach (self::PAYLOAD as $payload) {
            Property::firstOrCreate($payload);
        }
    }
}
